DEFAULT_FOLDER = monkey_typing/v1
MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
BOOTLOADER = atmel-dfu

AUDIO_SUPPORTED = no
KEYBOARD_SHARED_EP = no

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = bitbang
RGBLIGHT_ENABLE = yes

